sonar.projectKey=AJleX57_python-project-52
sonar.organization=AJleX57

sonar.sources=task_manager,users,statuses,tasks,labels
sonar.exclusions=**/migrations/**,**/tests.py,**/tests/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8